# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-25 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210811_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='fill_formModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('weekly_budget', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('lifestyle', models.CharField(max_length=50)),
                ('goals', models.CharField(max_length=50)),
                ('foods', models.CharField(max_length=50)),
            ],
        ),
    ]
