# Generated by Django 4.1 on 2023-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_makeapost_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="makeapost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="makeapost",
            name="name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
