# Generated by Django 4.2 on 2023-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_makeapost_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makeapost",
            name="description",
            field=models.CharField(blank=True, default="", max_length=256, null=True),
        ),
    ]
