# Generated by Django 4.1 on 2023-04-16 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0009_alter_makeapost_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=25, unique=True)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                ("description", models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("date", models.DateField(null=True)),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("total", models.CharField(default=0, max_length=10)),
                ("room", models.ManyToManyField(blank=True, to="myapp.room")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
