# Generated by Django 3.2.18 on 2023-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_makeapost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='subtotal',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
