# Generated by Django 3.2.18 on 2023-05-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='update',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
