# Generated by Django 3.2.18 on 2023-05-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20230524_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
